name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install dependencies (npm ci)
      run: npm ci
    - name: Build (npm run build)
      run: npm run build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.
        clean: true # Automatically remove deleted files from the deploy branch
        single-commit: true # keep only a single commit on the deploy branch
